# -*- ruby -*-

### ----------------------------------------------------------------------
### Copyright 2007 Alexey Radul.
### ----------------------------------------------------------------------
### This file is part of Probabilistic Scheme.
### 
### Probabilistic Scheme is free software; you can redistribute it and/or modify
### it under the terms of the GNU General Public License as published by
### the Free Software Foundation, either version 3 of the License, or
### (at your option) any later version.
### 
### Probabilistic Scheme is distributed in the hope that it will be useful,
### but WITHOUT ANY WARRANTY; without even the implied warranty of
### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
### GNU General Public License for more details.
### 
### You should have received a copy of the GNU General Public License
### along with Probabilistic Scheme.  If not, see <http://www.gnu.org/licenses/>.
### ----------------------------------------------------------------------

require 'rake'

task :default => :test

task :test do 
  sh %Q{mit-scheme --batch-mode --load all-tests.scm --eval "(%exit (run-registered-tests))"}
end

task :demo do 
  sh %Q{mit-scheme --batch-mode --load failure-report-demo.scm --eval "(%exit 0)"}
end

desc "Install the current version of this testing manager to /infolab/share/lib/testing"
task :install do
  sh "release --verbose --maintainer=axch@mit.edu . /infolab/share/lib/testing"
  sh "touch release-hack; release -w -v release-hack /infolab/share/lib/testing/WARNING; rm release-hack"
end
